In [6]:
#pip install -U imbalanced-learn

In [7]:
import numpy as np
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

In [20]:
# Example data with imbalanced classes
X = np.array([[1, 2],
              [20, 30],
              [30, 40],
              [40, 50],
              [50, 60]])
y = np.array([0, 1, 1, 1, 1])

In [21]:
# Display class distribution before oversampling
print("Class distribution before oversampling:", Counter(y))

Class distribution before oversampling: Counter({1: 4, 0: 1})


In [22]:
# Instantiate the RandomOverSampler
random_oversampler = RandomOverSampler(random_state=42)

In [23]:
# Perform random oversampling
X_resampled, y_resampled = random_oversampler.fit_resample(X, y)

In [24]:
# Display class distribution after oversampling
print("Class distribution after oversampling:", Counter(y_resampled))

Class distribution after oversampling: Counter({0: 4, 1: 4})


In [26]:
X_resampled

array([[ 1,  2],
       [20, 30],
       [30, 40],
       [40, 50],
       [50, 60],
       [ 1,  2],
       [ 1,  2],
       [ 1,  2]])

EX 02

In [32]:
# Set random seed for reproducibility
np.random.seed(42)

# Class 1: Values from a range of 2 to 9
class_1_data = np.random.randint(2, 10, size=(4, 2))
class_1_labels = np.ones(4, dtype=int)  # Class 1 label is 1

# Class 2: Values from a range of 12 to 19
class_2_data = np.random.randint(12, 20, size=(16, 2))
class_2_labels = np.zeros(16, dtype=int)  # Class 2 label is 0

# Combine data and labels for both classes
X = np.vstack([class_1_data, class_2_data])
y = np.concatenate([class_1_labels, class_2_labels])

# Display the generated data and labels
print("Original Data:")
print(X)
print("\Original Labels:")
print(y)

Original Data:
[[ 8  5]
 [ 6  8]
 [ 4  9]
 [ 6  6]
 [18 13]
 [14 18]
 [14 14]
 [19 16]
 [15 19]
 [19 14]
 [17 16]
 [13 19]
 [15 17]
 [17 13]
 [19 15]
 [16 12]
 [15 13]
 [17 16]
 [15 12]
 [12 14]]
\Original Labels:
[1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [28]:
# Instantiate the RandomOverSampler
random_oversampler = RandomOverSampler(random_state=42)

# Perform random oversampling
X_resampled, y_resampled = random_oversampler.fit_resample(X, y)

# Display class distribution after oversampling
print("Class distribution after oversampling:", Counter(y_resampled))

Class distribution after oversampling: Counter({1: 16, 0: 16})


In [31]:
print(X_resampled)

[[ 8  5]
 [ 6  8]
 [ 4  9]
 [ 6  6]
 [18 13]
 [14 18]
 [14 14]
 [19 16]
 [15 19]
 [19 14]
 [17 16]
 [13 19]
 [15 17]
 [17 13]
 [19 15]
 [16 12]
 [15 13]
 [17 16]
 [15 12]
 [12 14]
 [ 4  9]
 [ 6  6]
 [ 8  5]
 [ 4  9]
 [ 4  9]
 [ 6  6]
 [ 8  5]
 [ 8  5]
 [ 4  9]
 [ 6  8]
 [ 4  9]
 [ 4  9]]
