----------------
### Systematic sampling
--------------------

In [7]:
import random
import numpy as np

In [8]:
# data:
data = np.random.randint(low=10, high=99, size=60)  # This will create an array [0, 1, ..., 99]
data

array([50, 77, 63, 76, 68, 64, 71, 50, 60, 66, 85, 66, 77, 91, 35, 83, 11,
       61, 14, 98, 92, 74, 14, 90, 15, 41, 12, 39, 62, 67, 87, 78, 97, 41,
       44, 90, 84, 49, 35, 25, 97, 92, 94, 96, 53, 94, 33, 17, 33, 86, 37,
       10, 12, 32, 79, 57, 34, 93, 73, 19])

In [11]:
p

In [12]:
data

array([10, 11, 12, 12, 14, 14, 15, 17, 19, 25, 32, 33, 33, 34, 35, 35, 37,
       39, 41, 41, 44, 49, 50, 50, 53, 57, 60, 61, 62, 63, 64, 66, 66, 67,
       68, 71, 73, 74, 76, 77, 77, 78, 79, 83, 84, 85, 86, 87, 90, 90, 91,
       92, 92, 93, 94, 94, 96, 97, 97, 98])

#### Perform systematic sampling on data.
    
- Parameters:
    - data (list or numpy array): The data to sample from.
    - step (int): The sampling step.

- Returns:
    - List of sampled data.

In [13]:
step = 8

In [14]:
index = np.arange(start=0, stop=len(data), step=step)
index

array([ 0,  8, 16, 24, 32, 40, 48, 56])

`Note`: 
- This approach assumes that the initial starting point is the first item in the list or array. 
- If you want to start sampling from a random position within the first interval, you can adjust the start index appropriately.

In [15]:
# get the data for the selected index
data[index]

array([10, 19, 37, 53, 66, 77, 90, 96])

#### better example with TS data (stock prices)