In [2]:
from IPython.display import Image

In [1]:
import numpy as np

-------------------------------
#### Masking and Filtering
--------------------

`Index-based` selection is great, but what if we want to filter data based on more complicated `nonuniform` or `nonsequential` criteria? 

This is where the concept of a `mask` comes into play.

A `mask` is an array that has the `exact same shape as your data`, but instead of your values, it `holds Boolean values: either True or False`. 

You can use this mask array to index into your data array in `nonlinear and complex` ways. 

> It will `return` all of the elements where the Boolean array has a `True` value.

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
# broadcasting a value to multiple array positions
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr_slice = arr[5: 8]
arr_slice

array([12, 12, 12])

In [9]:
# change values in arr_slice, the mutations are reflected in the original 
# array arr
arr_slice[0] = 12345

In [10]:
arr_slice

array([12345,    12,    12])

In [11]:
arr

array([    0,     1,     2,     3,     4, 12345,    12,    12,     8,
           9])

In [12]:
# using : only means all values
arr_slice[1:2] = 9999

In [13]:
arr_slice

array([12345,  9999,    12])

In [15]:
arr

array([    0,     1,     2,     3,     4, 12345,  9999,    12,     8,
           9])

if you just assign a `portion of an array` to another array, the new array you just 
created actually `refers` to the parent array in memory.

That means, if you make any changes to the new array, it will reflect in the parent 
array as well.

So to avoid disturbing the parent array, you need to make a copy of it using copy(). 
All numpy arrays come with the `copy()` method.

##### deep copy method

In [15]:
arr_slice = arr[5:8].copy()

In [16]:
arr_slice

array([12345,  9999,    12])

In [17]:
arr_slice[:] = 888

In [18]:
arr_slice

array([888, 888, 888])

In [19]:
# the original array is not changed
arr

array([    0,     1,     2,     3,     4, 12345,  9999,    12,     8,
           9])

##### Boolean Indexing

In [23]:
names = np.array(['Rajat', 'Maruthi', 'Dinesh', 'Rajat', 'Bhanu', 'Viswa', 'Kamal'])

data  = np.random.randn(7, 4)

In [24]:
data

array([[-0.39366579, -0.09930185, -0.72218764,  0.50020901],
       [-0.079014  ,  0.10019103,  0.56298459, -1.11874638],
       [ 0.09235127, -1.6205526 , -1.78688022,  0.8109859 ],
       [ 0.02496329, -0.13070269,  0.15833103, -0.42424647],
       [-0.21742406, -0.14465438, -0.94126489,  1.4147899 ],
       [ 0.45888262, -0.12814819,  1.06262121, -0.0425459 ],
       [-0.01388148, -2.09675381, -0.86846121, -2.49319841]])

In [26]:
# Suppose each name corresponds to a row in the data array and we wanted to 
# select all the rows with corresponding name 'Rajat'.
names == 'Rajat'

array([ True, False, False,  True, False, False, False])

In [28]:
data[names == 'Rajat']

array([[-0.39366579, -0.09930185, -0.72218764,  0.50020901],
       [ 0.02496329, -0.13070269,  0.15833103, -0.42424647]])

> The boolean array must be of the `same length` as the array axis it’s indexing.

In [19]:
# what happens if they are of different lengths
names = np.array(['Rajat', 'Maruthi', 'Rajat', 'Bhanu', 'Viswa' ])
data = np.random.randn(7, 4)

In [20]:
data[names == 'Rajat']

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5

In [29]:
names = np.array(['Rajat', 'Maruthi', 'Dinesh', 'Rajat', 'Bhanu', 'Viswa', 'Kamal'])
data = np.random.randn(7, 4)
data

array([[ 0.67646158,  1.39376283, -0.6084103 , -0.40444405],
       [-1.24943898,  2.32885772, -0.09665378, -0.96369086],
       [ 0.52961159,  1.53088196, -0.94037358,  0.09738092],
       [ 0.74098544, -0.93914518,  0.50740314,  0.3759774 ],
       [ 0.47440038,  1.17870729,  0.01960889, -0.68320423],
       [ 0.04150486, -0.26984749, -0.24839721, -0.78199499],
       [ 0.07167279,  1.08336879,  1.17773126,  1.2596646 ]])

In [30]:
data[names == 'Kamal']

array([[-0.01388148, -2.09675381, -0.86846121, -2.49319841]])

In [31]:
data[names == 'Kamal', :2]

array([[-0.01388148, -2.09675381]])

In [32]:
data[names == 'Kamal', 2]

array([-0.86846121])

To select everything but 'Rajat', you can either use != or negate the condition using ~

In [33]:
names != 'Kamal'

array([ True,  True,  True,  True,  True,  True, False])

In [34]:
data[names != 'Kamal']

array([[-0.39366579, -0.09930185, -0.72218764,  0.50020901],
       [-0.079014  ,  0.10019103,  0.56298459, -1.11874638],
       [ 0.09235127, -1.6205526 , -1.78688022,  0.8109859 ],
       [ 0.02496329, -0.13070269,  0.15833103, -0.42424647],
       [-0.21742406, -0.14465438, -0.94126489,  1.4147899 ],
       [ 0.45888262, -0.12814819,  1.06262121, -0.0425459 ]])

In [35]:
data[~(names == 'Kamal')]

array([[-0.39366579, -0.09930185, -0.72218764,  0.50020901],
       [-0.079014  ,  0.10019103,  0.56298459, -1.11874638],
       [ 0.09235127, -1.6205526 , -1.78688022,  0.8109859 ],
       [ 0.02496329, -0.13070269,  0.15833103, -0.42424647],
       [-0.21742406, -0.14465438, -0.94126489,  1.4147899 ],
       [ 0.45888262, -0.12814819,  1.06262121, -0.0425459 ]])

In [36]:
cond = names == 'Kamal'

In [37]:
data[cond]

array([[-0.01388148, -2.09675381, -0.86846121, -2.49319841]])

In [39]:
data[~cond]

array([[-1.23817292,  2.30240272,  1.14984626,  1.64276385],
       [ 0.02340789,  0.87310484,  0.00371102,  0.19184094],
       [ 0.66886668,  1.02842207,  3.02740387,  0.76271729],
       [-1.75277634,  0.22566631, -1.0185516 , -1.07825174],
       [-0.43080966,  0.69669063,  1.68218469, -1.09664861],
       [-0.13176837, -2.54556952, -0.33191902, -0.58559732]])

Selecting two of the three names to combine multiple boolean conditions, 
use boolean arithmetic operators like & (and) and | (or):

In [40]:
cond = (names == 'Rajat') | (names == 'Bhanu')

In [41]:
data[cond]

array([[-1.23817292,  2.30240272,  1.14984626,  1.64276385],
       [-1.75277634,  0.22566631, -1.0185516 , -1.07825174],
       [-0.43080966,  0.69669063,  1.68218469, -1.09664861]])

In [23]:
cond = data > 0

In [24]:
cond

array([[ True, False,  True,  True],
       [ True, False, False,  True],
       [ True, False, False,  True],
       [ True, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True, False],
       [ True, False,  True, False]])

In [25]:
data[cond]

array([2.42401008, 0.21811244, 1.19586639, 0.67011704, 1.74282541,
       0.13106543, 1.06918389, 1.13283833, 0.59027478, 0.35565681,
       1.28397712, 1.46949258, 0.46664757, 0.46829406])